### ISSUE TITLE
How to make functions like esp?

### ISSUE THREAD

**Issue by yizhe-pro-max** [klinuxs/Arena-breakout-internal#1]
I'added my d3dhook from github(paste) and new dumped sdk with 
`    SDK::TArray<SDK::ULevel*>& levels = SDK::UWorld::GetWorld()->Levels;

    for (SDK::ULevel* Level : levels)
    {
        SDK::TArray<SDK::AActor*>& Actors = Level->Actors;
        for (SDK::AActor* Actor : Actors)
        {
            if (!Actor || !Actor->IsA(SDK::EClassCastFlags::Pawn) || !Actor->IsA(SDK::APawn::StaticClass()))
                continue;

            SDK::APawn* Pawn = static_cast<SDK::APawn*>(Actor);
            SDK::FVector Location = Pawn->GetTransform().Translation;
            std::string Name = Pawn->GetFullName();
            std::cout << Name << std::endl;
            // location is Location.x, so on so forth, and the name you need to do a contains check if its a player or not, just make a print if you want to see every players name and location
        }
    }
    SDK::UInputSettings::GetDefaultObj()->ConsoleKeys[0].KeyName = SDK::UKismetStringLibrary::Conv_StringToName(L"F2");
    SDK::UObject* NewObject = SDK::UGameplayStatics::SpawnObject(SDK::UEngine::GetEngine()->ConsoleClass, SDK::UEngine::GetEngine()->GameViewport);
    SDK::UEngine::GetEngine()->GameViewport->ViewportConsole = static_cast<SDK::UConsole*>(NewObject);`

Were pasted too.
What's next? Should i hook?

**Comment by klinuxs** [comment]
i dont understand, hook what?
